### ISSUE TITLE
Audio cannot be received in versions 6.0.4 and 6.0.5, but can be received in 6.0.3-pre

### ISSUE THREAD

**Issue by Hu-Said** [sipsorcery-org/SIPSorceryMedia.Windows#16]
**Part of the code is as follows:**
WindowsAudioEndPoint _winAudioEP = new WindowsAudioEndPoint(new AudioEncoder());
RTCConfiguration config = new() { iceServers = _iceServers, X_UseRtpFeedbackProfile = true };
_pc = new RTCPeerConnection(config);
 MediaStreamTrack audioTrack = new(_winAudioEP.GetAudioSinkFormats(), MediaStreamStatusEnum.SendRecv);
 _pc.addTrack(audioTrack);
_pc.OnAudioFormatsNegotiated += (audioFormats) =>
{
    AudioVideoSendService.AudioFormat = audioFormats.First();
    _winAudioEP.SetAudioSinkFormat(audioFormats.First());
};
_pc.OnRtpPacketReceived += (IPEndPoint rep, SDPMediaTypesEnum media, RTPPacket rtpPkt) =>
{
    if (media == SDPMediaTypesEnum.audio)
    {
        _winAudioEP.GotAudioRtp(rep, rtpPkt.Header.SyncSource, rtpPkt.Header.SequenceNumber, rtpPkt.Header.Timestamp, rtpPkt.Header.PayloadType, rtpPkt.Header.MarkerBit == 1, rtpPkt.Payload);
    }
};

**Comment by sipsorcery** [comment]
Give this [example](https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/SIPExamples/GetStarted/Program.cs) a try. It's the simplest one to test audio playback and is working fine with the latest versions fot eh lirbary for me.

**Comment by Hu-Said** [comment]
Yes, I tried the example you gave and I can indeed receive the message, but I still can’t receive the audio when I use it in the WebRTC example.
![image](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows/assets/63393002/da374579-9e0f-4e59-bd3f-caf392fceaaa)
Similarly, I can receive audio normally using 6.0.3-pre.

**Comment by Hu-Said** [comment]
I'm wondering if the way the new version is used in WebRTC has changed, or if there are some things that need to be configured.

**Comment by sipsorcery** [comment]
The example is working now.

It needs to be:

`await windowsAudioEP.StartAudioSink();`

not 

`await windowsAudioEP.StartAudio();`

That mechanism did change sometime in the last 2 years and I didn't spot it.

**Comment by Hu-Said** [comment]
Yes, I tried it and I can already receive the sound. Thank you very much for your reply. I hope sipsorcery will get better and better! In addition, I also hope there can be some documentation to help using this open source project. . .
