### ISSUE TITLE
OnVideoSourceEncodedSample of WindowsVideoEndPoint is not called periodically

### ISSUE THREAD

**Issue by TonyZhu2015** [sipsorcery-org/SIPSorceryMedia.Windows#8]
The video sampling from OnVideoSourceEncodedSample is jerky. as FrameArrivedHandler is not called at fixed intervals(the event is not raised for a long time. and all of a sudden, it is called a few times). This is a silly question that probably is non-relevant to [SIPSorceryMedia.Windows](https://github.com/sipsorcery-org/SIPSorceryMedia.Windows) project. I am new to video programming, is it caused by intensive cpu usage?

**Comment by dongxunzhang** [comment]
the same problem.Seeking a solution

**Comment by sipsorcery** [comment]
Yes, more likely CPU related although if you're using FFmpeg or libvpx native libraries for encoding it should cope fine.

A good test would be to reduce the frame rate and/or resolution and see if the problem persists. If it goes away then that does point to a CPU bottleneck.
